### PR TITLE
Relaxed error condition in syscall handler.

### PR DESCRIPTION
**Pull request by divan0v**
Errno has range from -1 to -__ELASTERROR. Another values in a0 should be
bypassed.

### CODE REVIEW

**Comment by divan0v** [comment]
Bump. Hello, I understand that this patch may be disputable. But could we discuss way that will be convenient for all?

**Comment by kito-cheng** [comment]
I think we can rewrite the `syscall_error` to a new inline function and then move the return code checking logic into that, and then `_sbrk` call `__internal_syscall` directly and check return code itself?

**Comment by divan0v** [comment]
Please, check corrected version.

**Comment by kito-cheng** [comment]
Hi Denis:

Only one thing need to fix, `__syscall_error (ENOMEM)` need change to `__syscall_error (-ENOMEM)` since `__syscall_error` will invert the sign of input argument [1], other part is OK.

Could you fix that? Thanks :)

[1] https://github.com/riscv/riscv-newlib/blob/riscv-newlib-3.0.0/libgloss/riscv/internal_syscall.h#L20

**Comment by divan0v** [comment]
Yes, you are very attentive :)

**Comment by kito-cheng** [comment]
Thanks!

**Comment by divan0v** [comment]
Hello, did you see corrected version?

**Comment by kito-cheng** [comment]
Ooop, I just forgot click the merge button.

**Pull request merged**
