### PR TITLE
Sync all headers from GCC

### PR DESCRIPTION
**Pull request by palmer-dabbelt**

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
@kito-cheng I don't know if this is sane, but it doesn't build unless I do this.

**Comment by kito-cheng** [comment]
No, I think it's cause by build flow, it can fix by build two stage for newlib toolchain, I have local change for that.

**Comment by kito-cheng** [comment]
https://github.com/riscv/riscv-gnu-toolchain/pull/221

**Comment by palmer-dabbelt** [comment]
@kito-cheng Thanks, that's a much better fix!

**Pull request closed without merging**
