### PR TITLE
Fix build newlib

### PR DESCRIPTION
**Pull request by kito-cheng**

### CODE REVIEW

**Comment by aswaterman** [comment]
Why get rid of the sbrk syscall?

**Comment by kito-cheng** [comment]
Bare Metal target (or riscv-elf target) almost don't implement sbrk syscall, riscv-gdb don't implement too.
and sbrk are implement by simple pointer arithmetic in all other target in newlib/libgloss.

**Comment by aswaterman** [comment]
Ok, but this is an incompatible change, and it breaks our existing
software. We can't merge it.

I guess we should be using a Newlib/Linux target, rather than
Newlib/libgloss.  We should consider fixing that.

I suggest you maintain your version on a branch in the mean time.

**Comment by kito-cheng** [comment]
Hmmm...how do you think I just implement a sbrk syscall in gdb simulator to prevent such incompatible change?

**Comment by aswaterman** [comment]
Hmm... it looks like some other gdb simulators (like https://github.com/riscv/riscv-binutils-gdb/blob/riscv-binutils-2.27/sim/rx/syscalls.c) provide a dummy implementation of sbrk.  We could add a similar hook on our ECALL instruction.

**Comment by kito-cheng** [comment]
OK, we will implement that next week.

**Pull request closed without merging**
