### PR TITLE
Moved syscalls to separate files to fix aliasing problems.

### PR DESCRIPTION
**Pull request by rishikhan**
Updated version of the isatty pull request that splits syscalls into independant files so there are no naming conflicts at link time.

### CODE REVIEW

**Comment by kito-cheng** [comment]
Thanks :)

**Comment by ilg-ul** [comment]
> so there are no naming conflicts at link time.

I'm trying to understand the reason for this. What naming conflicts? Normally the library should be compiled with `-ffunction-sections`, which creates a section for each function, regardless how they are grouped in files.

I'm trying to add semihosting support, and instead of dealing with a single file, I have to find a way to avoid several tens of them. :-(

**Comment by jim-wilson** [comment]
If all functions are in one file, and you call one of them, then the linker will be forced to bring in all of the functions.  This can be a problem if you only need one, and one of the others conflicts with a function in your program.  It is common for people to accidentally redefine library functions, as not everyone has every reserved function name memorized.  As a result, it is standard practice to put each library function in its own file.

Also, sometimes people will deliberately redefine a reserved function because they want it to work differently.  This can work only if each function is in its own file.

-ffunction-sections is not standard practice, as it breaks some programs, and may not work with all toolchain features. It can be very useful when it works, but you should not assume that it will always work.  Also, it doesn't change how the linker handles files, and hence doesn't fix naming conflicts.

If you are having trouble with the number of files, then that suggests you are doing something wrong.  If you don't want libgloss at all, then don't link with it.

**Comment by ilg-ul** [comment]
> If you are having trouble with the number of files, then that suggests you are doing something wrong. If you don't want libgloss at all, then don't link with it.

I don't need the ECALL libgloss, I want to implement the semihosting version of libgloss.

The plan was to add either a configure option, or even a simple preprocessor define (like USE_LIBGLOSS_SEMIHOSTING), and based on it to implement the syscalls differently. 

In the ECALL case I cannot evaluate the consequences, but for semihosting it is expected for all functions to be present and implement the semihosting functionality, so having them in a single file is not a problem. Actually in my implementation, inspired from ARM, I defined all functions as weak, but it is unusual for applications to redefine them.

And yes, I'm using `-ffunction-sections`, together with `-fdata-sections` and the linker `--gc-sections` for many years already and never had problmes with it. Actually all the projects generated by my Eclipse templates use this settings by default, and I had no compaints.

So, if I have a problem, it is that instead of having to edit one file, I have to edit several tens.

Do you have any suggestions on how to proceed with adding semihosting?

**Comment by rishikhan** [comment]
There is no ecall here … only scall.

And if you want to remove it, I suggest editing machine/syscall.h and putting some conditional preprocessor define there (that is set by a configure flag).

BTW. riscv-gcc will emit ecalls if it finds null dereferences and you are using -O2 or better.

**Comment by ilg-ul** [comment]
> editing machine/syscall.h and putting some conditional preprocessor define there

Accomodating the implementation for semihosting is slightly more complicated than replacing a macro.

https://github.com/micro-os-plus/semihosting-xpack/blob/xpack/src/syscalls-semihosting.cpp

> BTW. riscv-gcc will emit ecalls if it finds null dereferences

Last time I checked, code with undefined behaviour emited EBREAK.

**Comment by rishikhan** [comment]
understood. However, if you want to get rid of the scall, that’s where it is.

**Comment by ilg-ul** [comment]
> If you don't want libgloss at all, then don't link with it.

@jim-wilson, any suggestions how to do this with the official `riscv64-unknown-elf` toolchain?

**Pull request merged**
