### PR TITLE
Adding support for posix support:

### PR DESCRIPTION
**Pull request by rishikhan**
Adding support for posix support:
    * changes to configure.host to use posix
    * added from sysvi386: sys/dirent.h, sys/features.h, sys/termios.h, sys/utmp.h
    * added include/posix_opt.h to resolve features.h dependency
    * added to posix_opt.h: #define _UNIX98_THREAD_MUTEX_ATTRIBUTES 1 to support recurive mutexes (needed for libgomp)
    * added pthread.c with stub function defining pthread_setcancelstate to support posix io
    * changes to libc/machine/riscv/Makefile.am, Makefile.in to add pthread.c

### CODE REVIEW

**Comment by ilg-ul** [comment]
If I understand your patch right, you want to **always** add pthread support to newlib?

I don't mind adding the headers, but please be sure you still allow building newlib for bare-metal applications.

**Comment by rishikhan** [comment]
I wanted to add posix support (without pthreads), so I copied posix_opt.h from newlib/libc/sys/linux/linuxthreads/bits/posix_opt.h

Maybe it’s a bit aggressive in the definitions after line 75 (/* Tell we have POSIX threads.  */).

I am implementing a ‘bare metal’ pthreads library now to support libgomp. So, we will have support for bare-metal pthreads shortly [the mutex supports just sleeping until the locker wakes you up].

Because we have (#define _POSIX_THREADS  1) that sets up (_STDIO_WITH_THREAD_CANCELLATION_SUPPORT =1) and requires us to define pthread_setcancelstate as a no-op function.

What would you suggest? You can still compile and build newlib for bare-metal apps. You will have pthreads shortly.

**Comment by ilg-ul** [comment]
I would like you to make the additional pthreads support optional, using a configuration switch, so I don't have to patch your newlib to get rid of it.

**Comment by rishikhan** [comment]
Ok. I’ll work on that.

**Comment by ilg-ul** [comment]
thank you!

**Comment by jim-wilson** [comment]
This whole patch looks wrong to me.

For instance, you are adding utmp.h support copied from newlib/libc/sys/sysvi386, but this is OS specific support that is only enabled when configuring for that OS, which was a version of SCO.  You are copying this into newlib/libc/machine which is for bare metal support, but bare metal support implies no OS, so there is a serious contradiction here.

If you want OS support, then put it into a sys dir, and then configure for that OS instead of configuring for bare metal riscv.  Don't put OS support into bare metal riscv directories.

There are lots of other similar problems.  For instance, you are adding unix support to bare metal riscv support which is another contradiction.  You are adding a posix_opt.h file that claims that bare metal riscv has job control.  That makes no sense.  It looks like most of the posix_opt.h file is wrong.  You are adding pthread, dirent, and termios support none of which makes sense here.

Perhaps you should start from the beginning, and explain what problem you are trying to solve.

**Comment by rishikhan** [comment]
Sure. I’m trying to add posix I/O support and pthreads support (the latter by another library that I’ll commit soon … just trying to get newlib ready).

For the latter, I’ve already taken a repo maintainer’s advice to add a configure flag for whether that’s on or off. 

For the former (posix I/O), I’m trying to get fopen/fread, etc functions as well as file operations (like dirent stuff) via syscalls. 

Termios is not really my goal, but similarly available through sys calls.

Can you advise how you’d structure this?

Thanks!

Rishi

**Comment by sorear** [comment]
Newlib should be ecall FREE after fesvr has been updated to support the semihosting protocol.  POSIX I/O belongs in glibc, not here.

**Comment by jim-wilson** [comment]
It sounds like you are adding some type of semihosting support.  Your newlib patches can only work if everyone else has the exact same semihosting support.  But this semihosting support is not part of newlib, and there is no agreement currently on how semihosting should work.  So maybe these patches should not be part of newlib either.  Maybe there should be a separate BSP that includes both the semihosting support, and the posix support patches.

In general, the riscv support should be similar to other ports.  Other ports are not putting POSIX support into the machine dir, so the riscv port should not either.  There is one exception, the spu, but that is a special case.  The spu was one of the processors used in the PlayStation3, and I think that the newlib port assumes you have the PS3 SDK.

Otherwise, OS stuff should be in the sys dir.  The semihosting support will have to assume some OS ABI, so why not use one of the existing ones?  You could for instance add configure support for a riscv32-linux (and/or riscv64-linux) target that includes the posix, sys/linux, and unix directories.  See for instance how the i386-linux target support works.  You probably have to add a sys/riscv dir to add some missing target specific stuff.  There are also some other OS choices, like rtems.  Once you choose the OS, that defines the ABI, and how the semihosting support will have to interface with newlib.  People who want a different ABI/interface can use a different OS target.  I don't know of anyone actively using the newlib linux support though, so it might need some maintenance to get it working.  The rtems and cygwin support are in active use.  Or you could define your own OS and port newlib to it, putting the OS specific stuff in a new dir in sys, while reusing the existing unix/posix/linux stuff.

**Comment by ilg-ul** [comment]
Hi Jim, @jim-wilson, the semihosting details were already discussed, and I already have a functional ARM semihosting implementation for RISC-V targets added to the GNU MCU Eclipse OpenOCD (https://github.com/riscv/riscv-openocd/issues/185).

I also have a functional target implementation, running on HiFive1, E31Arty and E51Arty (https://github.com/micro-os-plus/semihosting-xpack/blob/xpack/src/syscalls-semihosting.cpp), already integrated in the GNU MCU Eclipse SiFive C/C++ Project Template, and you can easily generate projects with semihosting support.

Time permitting, I'll also add semihosting support to the GNU MCU RISC-V Embed GCC; the planned functionality will be similar to the ARM toolchain, i.e. using libgloss.

**Comment by rishikhan** [comment]
I’m not sure I understand this comment. glibc is a replacement for newlib. 

Also, fesvr is fine, but we need an ecall in libgloss to support the syscall proxy, correct?

**Comment by sorear** [comment]
The syscall proxy is obsolete now that we have semihosting, and I would like to remove it, so please do not add new dependencies on it.

**Comment by rishikhan** [comment]
Do you have any docs on this?

**Comment by rishikhan** [comment]
Ok, I've refactored all of this and moved it to the sys directory. Can you relook? Thanks!

**Comment by ilg-ul** [comment]
> Perhaps you should start from the beginning, and explain what problem you are trying to solve.

As Jim asked before, can you explain what type of applications do you target, what problems did you face and how do you plan to solve them?

The common use case for newlib is for bare-metal applications. In this case POSIX suport is 'retargetted' to local devices, by having the application implement the 'underscore' functions (like `_read()`, `_write()`, etc).

**Comment by rishikhan** [comment]
I get that the low level syscalls are retargeted or proxied. What about
fread/fwrite etc?

I'm trying to build an environment where one can run riscv programs on a
multicore chip but with no Linux os support. Syscalls are proxied out. But
higher level posix file stuff that is implemented in libc is still there
(fseek, fread, fwrite, etc). As it stands now, how does one do fopen in the
newlib we have today? That's what this patch enables.

For pthreads, every core has a thread (that is not preempted, but can sleep
to save power) and they talk through memory and atomics. Pthreads is a
separate library though.

**Comment by ilg-ul** [comment]
> What about fread/fwrite etc?

what about them? after a short journey inside newlib, they end in the user supplied `_read()`/`_write()`

> I'm trying to build an environment where one can run riscv programs on a
multicore chip but with no Linux os support. Syscalls are proxied out.

assuming you have a physical board with such a chip, how exactly do you run your programs?

> how does one do fopen in the newlib we have today? 

if I remember right, it calls an application supplied `_open()` which returns a unique file descriptor, that `_read()`/`_write()` test and implement accordingly.

**Comment by rishikhan** [comment]
Currently the riscv has no fopen. My patch enables this, and it ends in the
libgloss syscall to open(). So, I'm failing to see the problem here. open()
is already supported via syscalls. All I'm doing is adding the posix code
that enables all of the functions that eventually end up at these syscalls.

In my environment, programs are loader by a bootloader putting the program
in memory. The SP,PC are set and the core is off and running. The syscalls
call scall which traps into the proxy kernel. The proxy kernel talks to a
host through a memory mapped circular buffer.


On Feb 3, 2018 1:21 PM, "Liviu Ionescu" <notifications@github.com> wrote:

What about fread/fwrite etc?

what about them? after a short journey inside newlib, they end in the user
supplied _read()/_write()

I'm trying to build an environment where one can run riscv programs on a
multicore chip but with no Linux os support. Syscalls are proxied out.

assuming you have a physical board with such a chip, how exactly do you run
your programs?

how does one do fopen in the newlib we have today?

if I remember right, it calls an application supplied _open() which returns
a unique file descriptor, that _read()/_write() test and implement
accordingly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/riscv/riscv-newlib/pull/33#issuecomment-362842198>, or mute
the thread

**Comment by ilg-ul** [comment]
> Currently the riscv has no fopen. My patch enables this, and it ends in the
libgloss syscall to open(). 

I don't know what version of the toolchain you are using, but with the latest version of the GNU MCU Eclipse RISC-V Embed GCC I compile and run the following piece of code (generated by my Eclipse SiFive template) without any problems, with the syscalls implemented over the ARM semihosting API:

```c++
int
main (int argc, char* argv[])
{
  // Send a greeting to the trace device (skipped on Release).
  trace::puts ("Hello RISC-V World!");

  if (argc > 2)
    {
      // Example how to write/read a file to/from the host.
      // Usage should be no different than standard C/C++.
      // Pass a file name as command line second argument.
      int ret;

      ret = remove(argv[2]);
      trace::printf ("remove()=%d\n", ret);

      const char* buf = __DATE__ " " __TIME__;
      size_t buf_len = strlen(buf);

      FILE* fout = fopen(argv[2], "w");

      size_t len = fwrite(buf, 1, buf_len, fout);
      trace::printf ("fwrite()=%u\n", len);

      ret = fclose(fout);
      trace::printf ("fclose()=%d\n", ret);

      FILE* fin = fopen(argv[2], "r");

      char* buf_in = (char*)malloc(buf_len+1);
      len = fread(buf_in, 1, buf_len, fin);
      buf_in[len] = '\0';
      trace::printf ("fread()=%u\n", len);

      ret = fclose(fin);
      trace::printf ("fclose()=%d\n", ret);

      if (strncmp(buf, buf_in, buf_len) != 0) {
          exit(1);
      }
      trace::printf ("%s\n", buf_in);
    }

  // Send a message to the standard output.
  puts ("Standard output message.");

  // Send a message to the standard error.
  fprintf (stderr, "Standard error message.\n");

  // ...

}
```

I do not use any libgloss (since the current implementation does not meet my requirements), everything is in the application and in the standard newlib.

The above code runs on HiFive1, E31Arty, E51Arty, with a semihosting capable GDB server, like GNU MCU Eclipse OpenOCD.

**Comment by rishikhan** [comment]
Good point. I initially added posix for sleep and usleep. Then I got
confused between stdio and posix. So, sorry about that. You are right.

How would you suggest implementing sleep, usleep, nanosleep?

**Comment by ilg-ul** [comment]
> How would you suggest implementing sleep, usleep, nanosleep?

In my oppinion these are application dependent functions, that should be implemented by the application, not by newlib (or even libgloss), that should be as portable and application neutral as possible.

For example, in my µOS++, which is a real-time environment in C++, I have a POSIX IO subsystem, where you can define all kind of 'drivers' (as C++ classes), then use all standard I/O calls. Similarly for threads, mutexes, semaphores, etc. 

I don't need any such functions defined in newlib, since I don't want them to interfere with my environment.

**Comment by rishikhan** [comment]
I'd like to close this pull request. It's a mess. I've made a completely new one, pull #34 . Please look at that one.

**Pull request closed without merging**
